CREATE TABLE AUDI (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MODEL VARCHAR(255),
    COLOR VARCHAR(255),
    PRICE DECIMAL(10, 2)
);

INSERT INTO AUDI (MODEL, COLOR, PRICE) VALUES ('Audi A4', 'Red', 40000);
INSERT INTO AUDI (MODEL, COLOR, PRICE) VALUES ('Audi Q7', 'Black', 60000);
INSERT INTO AUDI (MODEL, COLOR, PRICE) VALUES ('Audi R8', 'White', 120000);
